# Documentation about Garden projects can be found at https://docs.garden.io/using-garden/projects
# Reference for Garden projects can be found at https://docs.garden.io/reference/project-config
apiVersion: garden.io/v1

# Indicate what kind of config this is.
kind: Project

# The name of the project.
name: kcp-playground

# A list of environments to configure for the project.
environments:
  - # The name of the environment.
    name: default
    variables:
      base-hostname: playground.garden

# A list of providers that should be used for this project, and their configuration. Please refer to individual
# plugins/providers for details on how to configure them.
providers:
  - # The name of the provider plugin to use.
    name: local-kubernetes
    environments: [default]
    namespace: ${environment.namespace}
    defaultHostname: ${var.base-hostname}
    ingressClass: nginx
